parserOptions:
  sourceType: module
  ecmaVersion: 9
  ecmaFeatures:
    jsx: true
env:
  es6: true
  node: true
plugins:
  - prettier
extends:
  - eslint:recommended
  - plugin:react/recommended
  - prettier
rules:
  prettier/prettier: error
