name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Setup Node.js v14
      uses: actions/setup-node@v2
      with:
        version: 14.x

    - name: Install dependencies
      run: yarn install --immutable

    - name: Check lint
      run: yarn lint

    - name: Check build
      run: yarn prepack
